### ISSUE TITLE
BUGS: Missing some fields on a tx that was created on MEW, also balances not updating

### ISSUE THREAD

**Issue by treeder** [gochain-io/explorer#44] opened 2018-05-30 21:05 UTC
https://explorer.gochain.io/tx/0xd33ddeaa2e94b047dcb86b5807373a8db024db23de7e3671ea4b12b41a35cbdb

![screen shot 2018-05-30 at 2 03 00 pm](https://user-images.githubusercontent.com/75826/40747456-33aea39c-6412-11e8-837a-c103ec552320.png)

In addition, user says his balance didn't update, it says 100, should be ~9: https://explorer.gochain.io/addr/0xb19cf6d5514883d40704d0e0cc1a29313e56c249

**Comment by jmank88** [comment] 2018-05-30 21:42
This is likely a pending tx which has not yet been included in a block. It would be included in any queries against 'pending'.

The fact that it was stuck in pending below the gas price limit is a separate problem, however, explorer could handle this case better by informing the user that the tx is pending.

**Comment by jmank88** [comment] 2018-06-01 17:46
The gas price inconsistency between proxies and signers has been resolved, and txs should no longer get 'stuck' in pending due to gas price being too low.

It is still possible to be legitimately pending for a period of time (long enough for a human to look it up), and Explorer should indicate that a transaction is pending when a block number is not included. Perhaps by literally displaying `Pending` in place of the 'Block Number' value. Or maybe a little more info, e.g. `Pending - Pooled but not yet processed`.

**Comment by jmank88** [comment] 2018-06-07 07:38
@chovy  Explorer should explicitly state that a transaction is pending when the block number is missing.

**Comment by chovy** [comment] 2018-06-07 15:53
ok

**Comment by chovy** [comment] 2018-06-07 19:36
@jmank88 i think i have it fixed but not sure how to test.

**Comment by chovy** [comment] 2018-06-07 20:58
@jmank88 please test live. I merged.

**Comment by jmank88** [comment] 2018-06-07 22:02
Confirmed live:
![screenshot from 2018-06-07 17-00-42](https://user-images.githubusercontent.com/1194128/41128603-614842dc-6a74-11e8-9d2a-f0d6cd1344dc.png)
Maybe we should do something with the `Time` field too.

**Comment by r-kononov** [comment] 2018-06-21 17:32
looks like could close this one

**Closed by r-kononov** 2018-06-21 17:32 UTC
Labels: bug
